# Generated by Django 2.0.3 on 2018-04-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180402_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('describe', models.TextField(blank=True, max_length=500)),
                ('gender', models.CharField(blank=True, max_length=5, null=True)),
                ('hobby', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, default='default.png', upload_to='users/%Y/%m/%d')),
            ],
        ),
    ]
