# Generated by Django 2.0.3 on 2018-04-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180425_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='identitycode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
