# Generated by Django 2.0.3 on 2018-04-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_friends_identitycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='identitycode',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
