# Generated by Django 2.0.3 on 2018-04-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='love')),
                ('thumbanils', models.ImageField(blank=True, upload_to='love/thumbanils')),
            ],
        ),
    ]
