# Generated by Django 2.0.3 on 2018-04-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovestory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='photo',
            field=models.ImageField(upload_to='love'),
        ),
    ]
