# Generated by Django 2.0.3 on 2018-04-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovestory', '0002_auto_20180405_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='words',
            field=models.CharField(blank=True, default='X & Y', max_length=70),
        ),
    ]
