# Generated by Django 2.0.3 on 2018-04-02 12:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnlogs', '0003_auto_20180324_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
