"""
Django settings for learninglog project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')b71m#fy__tiiy)v+a@l=upscepq35(*!po=17x3_udl62#@v*'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
import socket
if socket.gethostbyname(socket.gethostname())[:3]=='192':
    DEBUG = TEMPLATE_DEBUG = True
else:
    DEBUG = TEMPLATE_DEBUG = False


ALLOWED_HOSTS = ['*']
# ALLOWED_HOSTS = ['zongqiqi.ink','*.zongqiqi.ink'] 


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #我的应用
    'learnlogs',
    'users',  #用户系统
    'lovestory','bootstrap3',

    'django_comments','django.contrib.sites', #评论系统
    'rest_framework',   #restful api
    'ckeditor','ckeditor_uploader',  #富文本
]
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'learninglog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'learninglog/templates')],   ##自定义404,500页面
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'learninglog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

#支持国际化，国语言(Internationlization)
USE_I18N = True

USE_L10N = True

USE_TZ = True

##邮箱设置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_PORT= 25  
EMAIL_HOST = 'smtp.qq.com'  # 如果是 163 改成 smtp.163.com
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'zongqiqi0522@foxmail.com' # 帐号
EMAIL_HOST_PASSWORD = 'ryvpvvuqenybbbcf'  # 密码
DEFAULT_FROM_EMAIL = SERVER_EMAIL = EMAIL_HOST_USER
EMAIL_SUBJECT_PREFIX = 'website' #为邮件标题的前缀,默认是'[django]'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

#User拓展设置
AUTH_PROFILE_MODULE = 'users.Profile'

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'collected_static')
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    )

#多媒体文件
MEDIA_URL='/media/'  #访问多媒体文件的URL
MEDIA_ROOT=os.path.join(BASE_DIR,'media/')  ##多媒体文件的储存位置

CKEDITOR_UPLOAD_PATH = 'upload/'  #富文本上传地址

#未登录用户执行@login_required的操作是，重定向登陆页面
LOGIN_URL = '/users/login'


#RESTful --framework配置
REST_FRAMEWORK={
    'DEFAULT_PERMISSION_CLASSES':[ ##指定了去读取，创建，更新或者删除对象的默认权限
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'] #django-User权限，陌生人只读
}



##--log及通知管理员设置-------------------------
#管理员邮箱
# ADMINS = (
#     ('Zong Qiqi','zongqiqi0522@foxmail.com'),
# )
# #非空链接，却发生404错误，发送通知MANAGERS
# SEND_BROKEN_LINK_EMAILS = True
# MANAGERS = ADMINS
# #logging日志配置
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': True,
#     'formatters': {#日志格式 
#        'standard': {
#             'format': '%(asctime)s [%(threadName)s:%(thread)d] [%(name)s:%(lineno)d] [%(module)s:%(funcName)s] [%(levelname)s]- %(message)s'} 
#     },
#     'filters': {#过滤器
#         'require_debug_false': {
#                 '()': 'django.utils.log.RequireDebugFalse',
#             }
#     },
#     'handlers': {#处理器
#         'null': {
#             'level': 'DEBUG',
#             'class': 'logging.NullHandler',
#         },
#         'mail_admins': {#发送邮件通知管理员
#             'level': 'ERROR',
#             'class': 'django.utils.log.AdminEmailHandler',
#             'filters': ['require_debug_false'],# 仅当 DEBUG = False 时才发送邮件
#             'include_html': True,
#         },
#         'debug': {#记录到日志文件(需要创建对应的目录，否则会出错)
#             'level':'DEBUG',
#             'class':'logging.handlers.RotatingFileHandler',
#             'filename': os.path.join(BASE_DIR, "log",'debug.log'),#日志输出文件
#             'maxBytes':1024*1024*5,#文件大小 
#             'backupCount': 5,#备份份数
#             'formatter':'standard',#使用哪种formatters日志格式
#         },
#         'console':{#输出到控制台
#             'level': 'DEBUG',
#             'class': 'logging.StreamHandler',
#             'formatter': 'standard',
#         },
#     },
#     'loggers': {#logging管理器
#         'django': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#             'propagate': False 
#         },
#         'django.request': {
#             'handlers': ['debug','mail_admins'],
#             'level': 'ERROR',
#             'propagate': True,
#         },
#         # 对于不在 ALLOWED_HOSTS 中的请求不发送报错邮件
#         'django.security.DisallowedHost': {
#             'handlers': ['null'],
#             'propagate': False,
#         },
#     } 
# }

